import antfu from '@antfu/eslint-config'

export default antfu({
  ignores: ['node_modules/', '**/node_modules/**/', 'dist/', '**/dist/**/', '**/src-tauri/target/**', '**/src-tauri/gen/**', '**/src-tauri/permissions/autogenerated/**', 'logs/', '**/logs/**/', 'docs/', '**/docs/**/', 'coverage', '**/coverage/**', 'mcl', '**/mcl/**', 'go-cqhttp', '**/go-cqhttp/**'],
  formatters: true,
  unocss: true,
  vue: true,
}, {
  rules: {
    // for nest import
    'ts/consistent-type-imports': 'off',
  },
}, {
  files: ['apps/el-bot-client/**'],
  rules: {
    // This client uses semantic CSS classes rather than UnoCSS utilities.
    'unocss/order': 'off',
    'unocss/order-attributify': 'off',
  },
})
