[build]
publish = "docs/.vitepress/dist"
command = "pnpm install --frozen-lockfile && pnpm docs:build"

[build.environment]
# bypass npm auto install
NPM_FLAGS = "--version"
NODE_VERSION = "24.18.0"

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
