[package]
name = "el-bot-client"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "tray-icon" ] }
tauri-plugin-single-instance = "2"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
dirs = "6"
tokio = { version = "1", features = [
  "process",
  "time"
] }
