name: CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14", "16"]
        include:
          - node-version: "14"
            node-name: "LTS"
          - node-version: "16"
            node-name: "Latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i -g pnpm && pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check build
        run: pnpm build
